title: "Constanze’s Blog"
description: "Thoughts on neuro-tech, AI & HCI"
url: "https://constanzesa.github.io"

theme: minima
minima:
  skin: dark        # built-in dark palette

plugins:
  - jekyll-feed
