title: "Constanze’s Blog"
description: "Thoughts on neuro-tech, AI & HCI"
url: "https://constanzesa.github.io"

theme: minima
minima:
  skin: dark          # pure dark variant built into the theme

plugins:
  - jekyll-feed       # GitHub Pages white-lists this plugin
